config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later
    redirect_to edit_blog_post_path(@blog_post)
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_blog_post, except: %i[index new create]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at, :cover_image)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
  <div class="space-y-12">
    <div class="border-b border-gray-900/10 pb-12">

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="sm:col-span-4">
          <%= form.label :title, class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
              <%= form.text_field :title, class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6", placeholder: "title" %>
            </div>
            <div class="shadow-lg bg-white rounded-lg">
              <% @blog_post.errors.full_messages_for(:title).each do |message| %>
                <div class="rounded text-left font-semibold bg-red-100 text-red-600"><%= message %></div>
              <% end %>
            </div> 
          </div> 
        </div>

        <div class="col-span-full">
          <%= form.label :content, class: "block text-sm font-medium leading-6 text-gray-900"%>
          <div class="mt-2">
            <%= form.rich_text_area :content, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
          <div class="shadow-lg bg-white rounded-lg">
            <% @blog_post.errors.full_messages_for(:content).each do |message| %>
              <div class="rounded text-left font-semibold bg-red-100 text-red-600"><%= message %></div>
            <% end %>
          </div> 
        </div>    

        <div class="col-span-full">
          <%= form.label :cover_image, class: "block text-sm font-medium leading-6 text-gray-900"%>
          <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
            <div class="text-center">
              <% if @blog_post.cover_image.present? %>
                <div class="w-1/3 flex items-center justify-center gap-x-6">
                  <%= image_tag @blog_post.cover_image %>
                </div>
                <div class="mt-4 flex text-sm leading-6 text-gray-600">
                  <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you sure? Any other changes make will be lost." } %>
                </div>
                <% else %>
                <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
                </svg>
              <% end %>
              <div class="mt-4 flex text-sm leading-6 text-gray-600">
                <%= form.file_field :cover_image, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
              </div>
              <p class="text-xs leading-5 text-gray-600">PNG, JPG, GIF up to 10MB</p>
            </div>
          </div>
        </div>
      
        <div class="col-span-full">
          <div class="sm:col-span-3">
            <%= form.label :published_at, class: "block text-sm font-medium leading-6 text-gray-900" %>
            <div class="mt-2">
              <%= form.datetime_select :published_at, include_blank: true, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6" %>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="mt-6 flex items-center gap-x-6">
    <%= link_to "Back", root_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
    <button type="submit" class="rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600"><%= form.submit %></button>
  </div>
  <% end %>

app/views/blog_posts/edit.html.erb
<h2 class="text-base font-semibold leading-7 text-gray-900">Edit Post</h2>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600" %>

app/views/blog_posts/index.html.erb
<div class="grid grid-cols-1 gap-6">
  <% @blog_posts.each do |blog_post| %>
  <div class="shadow-lg bg-white rounded-lg">
    <% if blog_post.draft? %>
      <p class="rounded text-right font-semibold bg-gray-100 text-gray-600">Draft</p>
    <% elsif blog_post.scheduled? %>
      <p class="rounded text-right font-semibold bg-blue-100 text-blue-600">Scheduled</p>
    <% end %>
    <h3 class="mt-4 text-1xl text-center font-bold tracking-tight text-gray-900 sm:text-3xl">
      <%= link_to blog_post.title, blog_post %>
    </h3>
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <%= image_tag blog_post.cover_image if blog_post.cover_image.present? %>
    </div>
    <p class="mt-6 text-base leading-7 text-gray-600"><%= blog_post.content %></p>
  </div>
  <% end %>
</div>

<% if @pagy.count > @pagy.items %>
  <div class="m-10">
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h2 class="text-base font-semibold leading-7 text-gray-900">New Post</h2>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<div class="grid grid-cols-1 gap-6">
  <div class="shadow-lg bg-white rounded-lg">
    <h3 class="mt-4 text-1xl text-center font-bold tracking-tight text-gray-900 sm:text-3xl"><%= @blog_post.title %></h3>
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <%= image_tag @blog_post.cover_image if @blog_post.cover_image.present? %>
    </div>
    <p class="mt-6 text-base leading-7 text-gray-600"><%= @blog_post.content %></p>
    <div class="mt-10 flex items-center justify-center gap-x-6">
      <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "rounded-md bg-indigo-600 px-3.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" if user_signed_in? %>
      <%= link_to "Back", root_path, class: "text-sm font-semibold text-gray-900" %>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto bg-slate-100">
    <div class="lg:flex lg:items-center lg:justify-between">
      <div class="min-w-0 flex-1">
        <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">Welcome to Posts</h2>
      </div>

      <div class="mt-5 flex lg:ml-4 lg:mt-0">
        <% if user_signed_in? %>
        <span class="hidden sm:block">
          <button type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
            <%= link_to "New Post", new_blog_post_path %>
          </button>
        </span>
    
        <span class="ml-3 hidden sm:block">
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "inline-flex items-center rounded-md bg-red-50 px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-red-500" %>
        </span>
        <% else %>
        <span class="sm:ml-3">
            <%= link_to "Login", new_user_session_path, class: "inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </span>
        <% end %>
      </div>
    </div>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>
  </body>
</html>